### PR TITLE
Fix home path not found on windows

### LINKED ISSUE #231: Ritchie doesn't find the $HOME PATH with space
**What happened**:

Screen Shot 2020-08-14 at 18 00 45

**What you expected to happen**:

I expected Ritchie to find the correct path

**How to reproduce it (as minimally and precisely as possible)**:

- Use Windows OS with your $Home path with a space.

```
rit demo hello-world
```

**Anything else we need to know?**:

**Environment**:

- Ritchie version: 2.0.5

- Operating System: Windows

- Related ISSUE: https://github.com/ZupIT/ritchie-cli/issues/438

### PR DESCRIPTION
**Pull request by resmall**
# Pull Request

## What I did
Fixed the path issue with composite user names on Windows platform.

## How I did it
Removed all occurrences of `%%mypath:~0,-1%%/`, `%%mypath:~0,-1%%` and `%mypath:~0,-1%`.
Deleted all occurrences of `SET mypath=%%~dp0 >> %BAT_FILE%`.

## How to verify it
Create any formula on the Windows platform, where the logged user has a composite name such as "John Doe".

## What kind of change does this PR make

- [ ] Major
- [ ] Minor
- [x] Patch

## Description for the changelog
Fixes #231 the Windows "path not found" error

### CODE REVIEW

**Review by lucasdittrichzup — APPROVED** [review]

**Review by fabianofernandeszup — CHANGES_REQUESTED** [review]
Good afternoon, first thanks for your contribution.

We analyzed your PR and identified a possible problem. We use this% ~ dp0 feature as it points out the relative path from which the formula is being called.

Ex: If we call the execution from inside the formula folder, it would work without this parameter, but if the executor calls from another path, it would give an error. So by default we take this approach on both windows and linux.

Taking advantage of this, your PR was able to arrive at a solution that would serve both cases, solve the problem of paths with space and work relatively.

If you are interested in adjusting your PR, this is the solution and we will be happy to accept it.

echo 'start / B / D "% mypath%" / WAIT windows \ main.exe' >> $ (BAT)

**Comment by resmall** [comment]
Hi Fabiano, sure thing, I'll work on it.

**Comment by fabianofernandeszup** [comment]
Good morning @resmall , managed to evolve this PR?

**Comment by resmall** [comment]
Hey Fabiano, sorry for the delay, last two weeks have been busy. I'll look at it today.

**Comment by fabianofernandeszup** [comment]
Closed due to inactivity. We appreciate the contribution.
If you are interested in contributing again, check the list of issues to see if it is still open.

**Pull request closed without merging**
