### PR TITLE
Feature/language typescript

### PR DESCRIPTION
**Pull request by brunonmelo**
# Pull Request

## What I did
I created a new language template for Typespcript.

## How I did it
I used the allready existing Node template as base for create this new one.

## How to verify it
When you create a new formula, Typescript will be listed on the languages as an option.

## What kind of change does this PR make

- [ ] Major
- [x] Minor
- [ ] Patch

## Description for the changelog
Adding Typescript as a new language template option.

### CODE REVIEW

**Comment by brunonmelo** [comment]
This pull request is related to #184

**Review by GuillaumeFalourd — APPROVED** [review]

**Comment by GuillaumeFalourd** [comment]
Thank you for contributing @brunonmelo  👍

We are still working on the form for the Zup IT Challenge (https://insights.zup.com.br/hacktoberfest) and we'll send it to you as soon as it will be validated.

**Comment by brunonmelo** [comment]
I think it's missing the `hacktoberfest-accepted` tag.

**Comment by GuillaumeFalourd** [comment]
I added it @brunonmelo but it was not mandatory, as we added the `hacktoberfest` topic to the repository 👍

**Pull request merged**
